In this example I read and write json file using Jackson library
manolovv/project pull request #3
Opened 2024-01-15 16:31 UTC by manolovv

2024-01-16 18:55 UTC, xerZV requested changes
remove whole .idea folder from the project and commit/push. It is added in the .gitignore file but maybe after pushing the folder. It is hard for other contributors to work with your IDE workspace settings.

Overall great work, minimal changes required.
Keep up the great work, @manolovv

2024-01-16 18:55 UTC, xerZV commented on src/main/java/com/manolov/Main.java
> +        List<Vehicle> carList = mapper.readValue(new File("src\\main\\resources\\vehicles.json"),
this is a collection full of vehicles, rename the field properly

2024-01-16 18:55 UTC, xerZV commented on src/main/java/com/manolov/Main.java
> +        ObjectMapper objectMapper = new ObjectMapper();
you do not need second `ObjectMapper` instance, use the `ObjectMapper` instance created on line 17

2024-01-16 18:55 UTC, xerZV commented on src/main/java/com/manolov/architecture/Car.java
> +    private final String type = "Car";
this field can be constant

2024-01-16 18:55 UTC, xerZV commented on src/main/java/com/manolov/architecture/Motor.java
> +    private final String type = "Motor";
this field can be constant

2024-01-16 18:55 UTC, xerZV commented on src/main/resources/writeObjects.json
delete this file from the `resources` folder and add the file name in `.gitignore` file so next time you run the application the git will ignore this file and wont bring it to the remote.

2024-01-22 15:31 UTC, xerZV requested changes

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/Main.java
> +                new TypeReference<List<Vehicle>>() {
remove redundant `List<Vehicle>` in the `TypeReference`

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/Main.java
> +        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
duplicates `objectMapper.findAndRegisterModules();` - you have same thing in line 19

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/Main.java
> +
Is there a reason you deleted the line on which you save to JSON file?

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +    private TextField moreInformation;
use `String` instead

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +    private final String phoneNumber;
you can move this field to `User` class

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +        if (moreInformation != null) {
unnecessary if statement, just to `this.moreInformation = moreInformation`

2024-01-22 15:31 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +        if (moreInformation != null) {
unnecessary if statement, just to `this.moreInformation = moreInformation`

2024-01-22 16:22 UTC, manolovv commented on src/main/java/com/manolov/Main.java
> +        List<Vehicle> carList = mapper.readValue(new File("src\\main\\resources\\vehicles.json"),
I`ve done that

2024-01-22 16:23 UTC, manolovv commented on src/main/java/com/manolov/Main.java
> +                new TypeReference<List<Vehicle>>() {
its done

2024-01-22 16:29 UTC, manolovv commented on src/main/java/com/manolov/architecture/Ad.java
> +    private final String phoneNumber;
I must to remove the Ad class ?

2024-01-22 16:33 UTC, manolovv commented on src/main/java/com/manolov/Main.java
> +
You said to remove the json file in which i recorded info about the objects. Now i write in this json String

2024-01-22 16:52 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +    private final User user;
just a test comment on multiple lines so you can see how it looks

2024-01-22 16:53 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +    private final String phoneNumber;
you can move the `phoneNumber` field from `Ad` class to `User` class

2024-01-22 17:23 UTC, xerZV commented on src/main/java/com/manolov/architecture/Ad.java
> +import java.awt.*;
Unused import statement

2024-01-22 17:25 UTC, xerZV commented on src/main/java/com/manolov/architecture/Car.java
> +    private static final String CAR_TYPE = "Car";
this private field is never used - you can remove it

2024-01-22 17:25 UTC, xerZV commented on src/main/java/com/manolov/architecture/Motor.java
> +    private static final String MOTOR_TYPE = "Motor";
this private field is never used - you can remove it

2024-01-22 18:26 UTC, manolovv commented on src/main/java/com/manolov/architecture/Ad.java
> +        if (moreInformation != null) {
its already done

2024-01-22 21:09 UTC, xerZV approved these changes

2024-01-22 21:10 UTC, merged